MyDjangoStuff/Blog_finalv2/Blog_finalv2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register', include('django.contrib.auth.urls')),
    path('register', include('authentication.urls')),
    path('', include('posts.urls'))

]

MyDjangoStuff/Blog_finalv2/authentication/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'authentication'

urlpatterns = [
    path('', views.signup, name='signup'),
    path('/signin', views.signin, name='signin'),
    path('/signout', views.signout, name='signout'),
]

MyDjangoStuff/Blog_finalv2/posts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home')

]

MyDjangoStuff/Blog_finalv2/posts/models.py
from django.db import models

# Create your models here.

MyDjangoStuff/Blog_finalv2/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import form_class


class UserRegisterForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2",)

MyDjangoStuff/Blog_finalv2/authentication/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.mail import EmailMessage, send_mail
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login, logout
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse_lazy



def signup(request):
    form = UserProfileForm(request.POST)
    if request.method == "POST":
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']
        age = request.POST['age']

        if User.objects.filter(username=username):
            messages.error(request, "Username already exist! Please try some other username.")
            return render(request, "fail_page.html", {'reason': "Username already exist! Please try some other username."})

        if User.objects.filter(email=email).exists():
            messages.error(request, "Email Already Registered!!")
            return render(request, "fail_page.html", {'reason': "Email Already Registered!!"})

        if len(username)>20:
            messages.error(request, "Username must be under 20 charcters!!")
            return render(request, "fail_page.html", {'reason': "Username must be under 20 charcters!!"})

        if pass1 != pass2:
            messages.error(request, "Passwords didn't matched!!")
            return render(request, "fail_page.html", {'reason': "Passwords didn't matched!!"})

        if not username.isalnum():
            messages.error(request, "Username must be Alpha-Numeric!!")
            return render(request, "fail_page.html", {'reason': 'Username must be Alpha-Numeric!! (must contain atealst 1 letter)'})
        user = User.objects.create_user(username, email, pass1)
        return redirect('signin')
        # myuser.is_active = False
        #myuser.is_active = False

        messages.success(request, "Your Account has been created succesfully!!")
    return render(request, "authentication/signup.html", {'form': form})





def signin(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            login(request, user)
            fname = user.first_name
            # messages.success(request, "Logged In Sucessfully!!")
            return redirect('post_list')
        else:
            messages.error(request, "Bad Credentials!!")
            return render(request, "blog/fail_page.html", {'reason': "Bad Credentials!! (Password or username are wrong)"})

    return render(request, "authentication/signin.html")


def signout(request):
    logout(request)
    messages.success(request, "Logged Out Successfully!!")
    return redirect('post_list')

class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('post_list')

MyDjangoStuff/Blog_finalv2/posts/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'base.html')

MyDjangoStuff/Blog_finalv2/authentication/templates/authentication/password_change.html
{% extends "blog/base.html" %}
{% block content %}
<h1>Change Password</h1>

<div class="form-group">
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-success">Change Password</button>
  </form>
</div>
{% endblock %}

MyDjangoStuff/Blog_finalv2/authentication/templates/authentication/profile_change.html
{% extends "blog/base.html" %}
{% block content %}
  <h1>Change your {{title}}</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form.as_p}}
    <button type="submit" class='btn btn-success'>Save</button>
  </form>
{% endblock %}

MyDjangoStuff/Blog_finalv2/authentication/templates/authentication/signin.html
{% extends "base.html" %}
{% block content %}
{% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      <strong>Message:</strong> {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
  </div>
{% endfor %}

<h3>Log In to your account!</h3>
<form method="post" action="/signin" class="mb-2">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Enter Your Username" Required>
    </div>
    <div class="form-group">
        <label for="pass1">Password</label>
        <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Enter Your Password" Required>
    </div>

    <button type="submit" class="btn btn-primary">Log In</button>
</form>
{%endblock%}

MyDjangoStuff/Blog_finalv2/authentication/templates/authentication/signup.html
{% extends "base.html" %}
{% block content %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <strong>Message:</strong> {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div>
{% endfor %}

<h3>Create your account!</h3>
<form method="post" action="/signup" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Create A Username (use only letters and numbers)" Required>
    </div>
    <div class="form-group">
        <label for="fname">First Name</label>
        <input type="text" class="form-control" id="fname" name="fname" placeholder="Enter Your First Name" Required>
    </div>
    <div class="form-group">
        <label for="lname">Last Name</label>
        <input type="text" class="form-control" id="lname" name="lname" placeholder="Enter Your Last Name" Required>
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Your Email Address" Required>
    </div>
    <div class="form-group">
        <label for="pass1">Password</label>
        <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Create Your Password" Required>
    </div>
    <div class="form-group">
        <label for="pass2">Confirm Password</label>
        <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Confirm Your Password" Required>
    </div>
    {{form.media}}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Sign Up</button>
</form>

{% endblock %}

MyDjangoStuff/Blog_finalv2/authentication/templates/authentication/user_profile.html
{% extends "blog/base.html" %}
{% block content %}
  <div class="container">
    <h1 class="bigbrand techfont centerstage posttitle">Hello: {{user.userprofile.user}}</h1>
  </div><br>

  <div class="container">
    <img src="{{user.userprofile.profile_picture.url}}" alt="No profile picture yet! " class="profileimage  centerstage pf"><br>
    <br>
    <br>
    <br>
    <br>
  </div>
<hr>

{% if user.userprofile.bio %}
<div class="container">
  <h3 class="techfont">Bio: <br>{{user.userprofile.bio|safe}}</h3><br>
  <br>
  <br>
  <br>
{%else%}
  <h3>class="techfont">No bio yet!</h3>
{%endif%}
</div>
<hr>
<h2 class="techfont">Change password: <a href="{%url 'authentication:password_change'%}">Change password</a></h2>
<br>
<br>
<br>
<br>
<h2 class="techfont"><a href="{%url 'authentication:profilechange' pk=user.userprofile.pk%}">Change your profile</a></h2>


{%if posts%}
<h3>Posts by author:</h3>
{% for post in  posts%}
  <h4 class="techfont"><a href="{% url 'post_detail' pk=post.pk %}">{{post.title}}</a></h4>
{% endfor %}
{%else%}
<a class="techfont" href="{%url 'post_new'%}">No posts yet.... why dont you write one :)</a><br><br><br>
{%endif%}


<a class="techfont" href="{% url 'authentication:signout' %}" >Log out</a>







{% endblock %}

MyDjangoStuff/Blog_finalv2/authentication/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content %}

    {% endblock %}
  </body>
</html>